import type { Ingredient, Recipe } from '@/domain/types'
import { uid } from '@/domain/kitchen'

type SeedIngredient = Omit<Ingredient, 'id' | 'createdAt'>

export const SEED_INGREDIENTS: SeedIngredient[] = [
  {
    name: 'Short-grain rice',
    category: 'staples',
    unit: 'g',
    nutritionPer100: { energyKcal: 358, fatG: 0.6, carbsG: 79, proteinG: 6.7 },
    lowStockThreshold: 200,
  },
  {
    name: 'Soba noodles',
    category: 'staples',
    unit: 'g',
    nutritionPer100: { energyKcal: 336, fatG: 1.1, carbsG: 71, proteinG: 14 },
    lowStockThreshold: 100,
  },
  {
    name: 'Chicken breast',
    category: 'proteins',
    unit: 'g',
    nutritionPer100: { energyKcal: 110, fatG: 1.2, carbsG: 0, proteinG: 23 },
    lowStockThreshold: 200,
  },
  {
    name: 'Salmon fillet',
    category: 'proteins',
    unit: 'g',
    nutritionPer100: { energyKcal: 208, fatG: 13, carbsG: 0, proteinG: 20 },
    lowStockThreshold: 150,
  },
  {
    name: 'Firm tofu',
    category: 'proteins',
    unit: 'g',
    nutritionPer100: { energyKcal: 78, fatG: 4.8, carbsG: 1.9, proteinG: 8.1 },
    lowStockThreshold: 200,
  },
  {
    name: 'Eggs',
    category: 'proteins',
    unit: 'pcs',
    avgPieceGrams: 55,
    nutritionPer100: { energyKcal: 143, fatG: 9.5, carbsG: 0.7, proteinG: 12.6 },
    lowStockThreshold: 4,
  },
  {
    name: 'Napa cabbage',
    category: 'vegetables',
    unit: 'g',
    nutritionPer100: { energyKcal: 16, fatG: 0.2, carbsG: 3.2, proteinG: 1.2 },
    lowStockThreshold: 200,
  },
  {
    name: 'Carrot',
    category: 'vegetables',
    unit: 'g',
    nutritionPer100: { energyKcal: 41, fatG: 0.2, carbsG: 10, proteinG: 0.9 },
    lowStockThreshold: 150,
  },
  {
    name: 'Spring onion',
    category: 'vegetables',
    unit: 'g',
    nutritionPer100: { energyKcal: 32, fatG: 0.2, carbsG: 7, proteinG: 1.8 },
    lowStockThreshold: 50,
  },
  {
    name: 'Shiitake mushrooms',
    category: 'vegetables',
    unit: 'g',
    nutritionPer100: { energyKcal: 34, fatG: 0.5, carbsG: 7, proteinG: 2.2 },
    lowStockThreshold: 100,
  },
  {
    name: 'Spinach',
    category: 'vegetables',
    unit: 'g',
    nutritionPer100: { energyKcal: 23, fatG: 0.4, carbsG: 3.6, proteinG: 2.9 },
    lowStockThreshold: 100,
  },
  {
    name: 'Daikon radish',
    category: 'vegetables',
    unit: 'g',
    nutritionPer100: { energyKcal: 18, fatG: 0.1, carbsG: 4.1, proteinG: 0.6 },
    lowStockThreshold: 200,
  },
  {
    name: 'Edamame',
    category: 'vegetables',
    unit: 'g',
    nutritionPer100: { energyKcal: 121, fatG: 5.2, carbsG: 8.9, proteinG: 11.9 },
    lowStockThreshold: 150,
  },
  {
    name: 'Nori sheets',
    category: 'seaweed',
    unit: 'pcs',
    avgPieceGrams: 3,
    nutritionPer100: { energyKcal: 35, fatG: 0.3, carbsG: 5, proteinG: 6 },
    lowStockThreshold: 5,
  },
  {
    name: 'Kombu',
    category: 'seaweed',
    unit: 'g',
    nutritionPer100: { energyKcal: 43, fatG: 0.6, carbsG: 10, proteinG: 1.7 },
    lowStockThreshold: 20,
  },
  {
    name: 'Katsuobushi',
    category: 'seaweed',
    unit: 'g',
    nutritionPer100: { energyKcal: 356, fatG: 3.5, carbsG: 0.5, proteinG: 77 },
    lowStockThreshold: 20,
  },
  {
    name: 'White miso',
    category: 'ferments',
    unit: 'g',
    nutritionPer100: { energyKcal: 199, fatG: 6, carbsG: 26, proteinG: 12 },
    lowStockThreshold: 50,
  },
  {
    name: 'Soy sauce',
    category: 'ferments',
    unit: 'ml',
    nutritionPer100: { energyKcal: 53, fatG: 0.1, carbsG: 5, proteinG: 8 },
    lowStockThreshold: 50,
  },
  {
    name: 'Mirin',
    category: 'ferments',
    unit: 'ml',
    nutritionPer100: { energyKcal: 241, fatG: 0, carbsG: 45, proteinG: 0.1 },
    lowStockThreshold: 50,
  },
  {
    name: 'Rice vinegar',
    category: 'ferments',
    unit: 'ml',
    nutritionPer100: { energyKcal: 18, fatG: 0, carbsG: 0.5, proteinG: 0 },
    lowStockThreshold: 50,
  },
  {
    name: 'Sesame oil',
    category: 'oils',
    unit: 'ml',
    nutritionPer100: { energyKcal: 884, fatG: 100, carbsG: 0, proteinG: 0 },
    lowStockThreshold: 30,
  },
  {
    name: 'Neutral oil',
    category: 'oils',
    unit: 'ml',
    nutritionPer100: { energyKcal: 884, fatG: 100, carbsG: 0, proteinG: 0 },
    lowStockThreshold: 50,
  },
  {
    name: 'Toasted sesame seeds',
    category: 'spices',
    unit: 'g',
    nutritionPer100: { energyKcal: 573, fatG: 50, carbsG: 23, proteinG: 18 },
    lowStockThreshold: 20,
  },
  {
    name: 'Ginger',
    category: 'spices',
    unit: 'g',
    nutritionPer100: { energyKcal: 80, fatG: 0.8, carbsG: 18, proteinG: 1.8 },
    lowStockThreshold: 20,
  },
  {
    name: 'Garlic',
    category: 'spices',
    unit: 'g',
    nutritionPer100: { energyKcal: 149, fatG: 0.5, carbsG: 33, proteinG: 6.4 },
    lowStockThreshold: 20,
  },
  {
    name: 'Sugar',
    category: 'sweeteners',
    unit: 'g',
    nutritionPer100: { energyKcal: 387, fatG: 0, carbsG: 100, proteinG: 0 },
    lowStockThreshold: 50,
  },
  {
    name: 'Cucumber',
    category: 'vegetables',
    unit: 'g',
    nutritionPer100: { energyKcal: 15, fatG: 0.1, carbsG: 3.6, proteinG: 0.7 },
    lowStockThreshold: 150,
  },
  {
    name: 'Wakame (dried)',
    category: 'seaweed',
    unit: 'g',
    nutritionPer100: { energyKcal: 45, fatG: 0.6, carbsG: 9, proteinG: 3 },
    lowStockThreshold: 15,
  },
]

function step(
  description: string,
  timer?: { duration: number; unit: 'seconds' | 'minutes' | 'hours' },
  group?: string,
) {
  return {
    id: uid(),
    description,
    requiresTimer: Boolean(timer),
    timerDuration: timer?.duration,
    timerUnit: timer?.unit,
    group,
  }
}

/** Recipes reference ingredients by name; resolved to IDs during seed. */
export type SeedRecipeDraft = Omit<
  Recipe,
  'id' | 'createdAt' | 'updatedAt' | 'ingredients'
> & {
  ingredientNames: { name: string; amount: number }[]
}

export const SEED_RECIPE_DRAFTS: SeedRecipeDraft[] = [
  {
    name: 'Everyday miso soup',
    description: 'A calming bowl of dashi, wakame, tofu, and white miso — batch the dashi base.',
    tip: 'Never boil miso; whisk it in off the heat to keep the flavour soft.',
    category: 'soup',
    effort: 'easy',
    portions: 4,
    storageDays: 3,
    storageEnv: 'fridge',
    seeded: true,
    steps: [
      step('Soak wakame in cool water until soft, then drain.', undefined, 'Wakame'),
      step('Simmer kombu in 1 L water for 10 minutes; remove kombu.', {
        duration: 10,
        unit: 'minutes',
      }, 'Dashi'),
      step('Add katsuobushi, steep 3 minutes, strain dashi.', { duration: 3, unit: 'minutes' }, 'Dashi'),
      step('Add cubed tofu and wakame; warm gently.', undefined, 'Soup'),
      step('Turn off heat; whisk in miso until dissolved. Finish with spring onion.', undefined, 'Soup'),
    ],
    ingredientNames: [
      { name: 'White miso', amount: 60 },
      { name: 'Firm tofu', amount: 200 },
      { name: 'Wakame (dried)', amount: 8 },
      { name: 'Kombu', amount: 10 },
      { name: 'Katsuobushi', amount: 15 },
      { name: 'Spring onion', amount: 40 },
    ],
  },
  {
    name: 'Batch short-grain rice',
    description: 'Fluffy Japanese rice for the week — cool, portion, and reheat gently.',
    tip: 'Rinse until the water runs almost clear; rest 10 minutes after cooking.',
    category: 'rice',
    effort: 'easy',
    portions: 6,
    storageDays: 4,
    storageEnv: 'fridge',
    seeded: true,
    steps: [
      step('Rinse rice in cool water until mostly clear.', undefined, 'Rice'),
      step('Soak 20 minutes, then drain.', { duration: 20, unit: 'minutes' }, 'Rice'),
      step('Cook with equal water by volume; simmer covered 12 minutes.', {
        duration: 12,
        unit: 'minutes',
      }, 'Cook'),
      step('Rest off heat, covered, 10 minutes. Fluff with a rice paddle.', {
        duration: 10,
        unit: 'minutes',
      }, 'Cook'),
    ],
    ingredientNames: [{ name: 'Short-grain rice', amount: 600 }],
  },
  {
    name: 'Ginger chicken simmer',
    description: 'Tender chicken breast gently simmered with soy, mirin, and ginger.',
    tip: 'Slice against the grain after resting so the meat stays juicy when reheated.',
    category: 'simmered',
    effort: 'medium',
    portions: 4,
    storageDays: 3,
    storageEnv: 'fridge',
    seeded: true,
    steps: [
      step('Slice chicken into bite-size pieces; grate ginger.', undefined, 'Prep'),
      step('Combine soy, mirin, a splash of water, and ginger in a pan.', undefined, 'Sauce'),
      step('Add chicken; simmer gently 12 minutes until just cooked.', {
        duration: 12,
        unit: 'minutes',
      }, 'Simmer'),
      step('Reduce sauce briefly; finish with spring onion.', undefined, 'Finish'),
    ],
    ingredientNames: [
      { name: 'Chicken breast', amount: 500 },
      { name: 'Soy sauce', amount: 40 },
      { name: 'Mirin', amount: 40 },
      { name: 'Ginger', amount: 20 },
      { name: 'Spring onion', amount: 30 },
      { name: 'Sugar', amount: 10 },
    ],
  },
  {
    name: 'Miso-glazed salmon',
    description: 'Salmon fillets brushed with miso-mirin glaze — excellent cold or reheated.',
    tip: 'Pat fish dry so the glaze caramelises instead of steaming.',
    category: 'grilled',
    effort: 'medium',
    portions: 4,
    storageDays: 3,
    storageEnv: 'fridge',
    seeded: true,
    steps: [
      step('Mix white miso, mirin, and a touch of sugar into a paste.', undefined, 'Glaze'),
      step('Coat salmon; marinate 20 minutes.', { duration: 20, unit: 'minutes' }, 'Glaze'),
      step('Bake or pan-sear until just opaque, about 10 minutes.', {
        duration: 10,
        unit: 'minutes',
      }, 'Cook'),
    ],
    ingredientNames: [
      { name: 'Salmon fillet', amount: 500 },
      { name: 'White miso', amount: 40 },
      { name: 'Mirin', amount: 30 },
      { name: 'Sugar', amount: 8 },
    ],
  },
  {
    name: 'Spinach goma-ae',
    description: 'Blanched spinach dressed with toasted sesame — a light side for every meal.',
    tip: 'Squeeze spinach thoroughly so the dressing clings instead of pooling.',
    category: 'sides',
    effort: 'easy',
    portions: 4,
    storageDays: 2,
    storageEnv: 'fridge',
    seeded: true,
    steps: [
      step('Blanch spinach 45 seconds; plunge into ice water.', {
        duration: 45,
        unit: 'seconds',
      }, 'Spinach'),
      step('Squeeze dry; cut into lengths.', undefined, 'Spinach'),
      step('Crush sesame seeds; mix with soy and a pinch of sugar. Toss with spinach.', undefined, 'Dressing'),
    ],
    ingredientNames: [
      { name: 'Spinach', amount: 300 },
      { name: 'Toasted sesame seeds', amount: 30 },
      { name: 'Soy sauce', amount: 20 },
      { name: 'Sugar', amount: 5 },
    ],
  },
  {
    name: 'Kinpira-style carrots & daikon',
    description: 'Julienned root vegetables stir-fried and simmered in a sweet-savoury glaze.',
    tip: 'Keep the heat medium so the vegetables stay crisp-tender through the week.',
    category: 'stirfry',
    effort: 'easy',
    portions: 4,
    storageDays: 4,
    storageEnv: 'fridge',
    seeded: true,
    steps: [
      step('Julienne carrot and daikon into matchsticks.', undefined, 'Prep'),
      step('Stir-fry in a little oil 3 minutes.', { duration: 3, unit: 'minutes' }, 'Stir-fry'),
      step('Add soy, mirin, and sugar; simmer until glaze coats, about 5 minutes.', {
        duration: 5,
        unit: 'minutes',
      }, 'Glaze'),
      step('Finish with sesame seeds.', undefined, 'Finish'),
    ],
    ingredientNames: [
      { name: 'Carrot', amount: 250 },
      { name: 'Daikon radish', amount: 250 },
      { name: 'Neutral oil', amount: 15 },
      { name: 'Soy sauce', amount: 25 },
      { name: 'Mirin', amount: 25 },
      { name: 'Sugar', amount: 10 },
      { name: 'Toasted sesame seeds', amount: 10 },
    ],
  },
  {
    name: 'Quick cucumber pickles',
    description: 'Lightly salted cucumbers with rice vinegar — bright contrast to rich dishes.',
    tip: 'Salt first to draw water, then dress; they stay crisp longer.',
    category: 'sides',
    effort: 'easy',
    portions: 4,
    storageDays: 5,
    storageEnv: 'fridge',
    seeded: true,
    steps: [
      step('Slice cucumber thin; toss with salt and rest 15 minutes.', {
        duration: 15,
        unit: 'minutes',
      }),
      step('Rinse, squeeze gently, dress with rice vinegar and a pinch of sugar.'),
    ],
    ingredientNames: [
      { name: 'Cucumber', amount: 300 },
      { name: 'Rice vinegar', amount: 40 },
      { name: 'Sugar', amount: 8 },
      { name: 'Sesame oil', amount: 5 },
    ],
  },
  {
    name: 'Tamago soba bowl base',
    description: 'Chilled or warm soba with soft eggs — build bowls through the week.',
    tip: 'Cook noodles just shy of done; they soften when reheated in broth.',
    category: 'bowl',
    effort: 'medium',
    portions: 4,
    storageDays: 3,
    storageEnv: 'fridge',
    seeded: true,
    steps: [
      step('Boil soba according to pack; rinse under cold water.', {
        duration: 5,
        unit: 'minutes',
      }, 'Noodles'),
      step('Soft-boil eggs 7 minutes; ice bath and peel.', { duration: 7, unit: 'minutes' }, 'Eggs'),
      step('Portion noodles; store eggs separately. Serve with soy or dashi later.', undefined, 'Assembly'),
    ],
    ingredientNames: [
      { name: 'Soba noodles', amount: 320 },
      { name: 'Eggs', amount: 4 },
      { name: 'Soy sauce', amount: 30 },
      { name: 'Spring onion', amount: 40 },
      { name: 'Nori sheets', amount: 2 },
    ],
  },
  {
    name: 'Braised tofu with mushrooms',
    description: 'Firm tofu and shiitake simmered in a light soy-mirin broth.',
    tip: 'Press tofu 10 minutes first so it absorbs the seasoning.',
    category: 'simmered',
    effort: 'easy',
    portions: 4,
    storageDays: 3,
    storageEnv: 'fridge',
    seeded: true,
    steps: [
      step('Press tofu; cube. Slice shiitake.', undefined, 'Prep'),
      step('Sauté mushrooms in a little oil until fragrant.', undefined, 'Mushrooms'),
      step('Add tofu, soy, mirin, and water; simmer 10 minutes.', {
        duration: 10,
        unit: 'minutes',
      }, 'Simmer'),
      step('Finish with sesame oil and spring onion.', undefined, 'Finish'),
    ],
    ingredientNames: [
      { name: 'Firm tofu', amount: 400 },
      { name: 'Shiitake mushrooms', amount: 200 },
      { name: 'Soy sauce', amount: 30 },
      { name: 'Mirin', amount: 30 },
      { name: 'Sesame oil', amount: 10 },
      { name: 'Spring onion', amount: 30 },
      { name: 'Neutral oil', amount: 10 },
    ],
  },
  {
    name: 'Garlic edamame',
    description: 'Warm edamame tossed with garlic and a splash of soy — snack or side.',
    tip: 'Dry the pods well before tossing so the garlic sticks.',
    category: 'sides',
    effort: 'easy',
    portions: 4,
    storageDays: 3,
    storageEnv: 'fridge',
    seeded: true,
    steps: [
      step('Boil edamame 4 minutes; drain well.', { duration: 4, unit: 'minutes' }, 'Pods'),
      step('Sauté minced garlic in sesame oil 30 seconds.', { duration: 30, unit: 'seconds' }, 'Garlic oil'),
      step('Toss pods with garlic oil and soy. Serve warm or cold.', undefined, 'Toss'),
    ],
    ingredientNames: [
      { name: 'Edamame', amount: 400 },
      { name: 'Garlic', amount: 12 },
      { name: 'Sesame oil', amount: 10 },
      { name: 'Soy sauce', amount: 15 },
    ],
  },
]
